name: Publish report to gh-pages
description: That workflow will publish report to the github-pages
inputs:
  sub-folder:
    description: 'Sub folder where the results will be published'
    required: true
  secret-token:
    description: 'Secret token for gh deployment'
    required: true
  keep-reports-history:
    description: 'History storage depth, integer'
    required: true
  artifact-name:
    description: 'Name of downloading artifacts'
    required: true
  artifact-path:
    description: 'Path for downloading artifacts'
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Unzip results
        run: |
          cd ${{ inputs.artifact-path }}
          tar -xvf allure-results.tar
        shell: bash

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          repository: nova-wallet/test-runner
          ref: gh-pages
          path: gh-pages

      - name: Debug
        run: |
          ls -R
        shell: bash

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ inputs.artifact-path }}/allure-results
          allure_history: allure-history
          keep_reports: ${{ inputs.keep-reports-history }}
          subfolder: ${{ inputs.sub-folder }}

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ inputs.secret-token }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
