name: Networks healthcheck

on:
  schedule:
    - cron: '0 0/4 * * *'
  workflow_dispatch:
  pull_request:

env:
  ACALA_PROD_AUTH_TOKEN: 'token'
  ACALA_TEST_AUTH_TOKEN: 'token'
  MOONBEAM_PROD_AUTH_TOKEN: 'token'
  MOONBEAM_TEST_AUTH_TOKEN: 'token'
  MOONPAY_PRODUCTION_SECRET: 'token'
  MOONPAY_TEST_SECRET: 'token'

  CI_KEYSTORE_PASS: 'token'
  CI_KEYSTORE_KEY_ALIAS: 'token'
  CI_KEYSTORE_KEY_PASS: 'token'

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          repository: nova-wallet/nova-wallet-android
          ref: 'develop'
          token: ${{ secrets.PAT }}

      - name: ☕️ Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: 🏗 Build app for testing
        run: ./gradlew :app:assembleDebugAndroidTest

      - name: 🧪 Build instrumential test
        run: ./gradlew :app:assembleInstrumentialTest

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: |
            app/build/outputs/apk/instrumentialTest/
            app/build/outputs/apk/androidTest/debug/


  test:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: apk
          path: app

      - name: Debug
        run: |
          ls -R

      - name: Add permissions
        run: chmod +x .github/workflows/networks_test.sh

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          disable-animations: true
          profile: Nexus 5X
          api-level: 28
          script: .github/workflows/networks_test.sh

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: report
          path: ./allure-results.tar

  report:
    runs-on: ubuntu-latest
    needs: test
    if: always() && (needs.build.result == 'success')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: report
          path: ./

      - name: Unzip results
        run: |
          mkdir results
          tar -xvf allure-results.tar -C ./results

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Debug
        run: |
          ls -R

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: results
          allure_history: allure-history
          keep_reports: 30
          subfolder: android-tests

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  alert:
    runs-on: ubuntu-latest
    needs: report
    if: always() && (needs.test.result == 'failure')
    env:
      GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Network tests failed, lets check:

            Failed run:
            ${{ env.GITHUB_WORKFLOW_URL }}

            Report:
            https://nova-wallet.github.io/test-runner/${{ github.run_number }}
