name: Check nodes availability

on:
  workflow_dispatch:
  pull_request:

env:
  SUB_FOLDER: utils-tests
  TEST_RE_RUNS: 1
  TEST_RE_RUNS_DELAY: 10

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        tests:
          [
            ./tests/test_nodes_availability.py,
            ./tests/test_network_parameters.py,
            ./tests/test_xcm_data.py,
          ]
    steps:
      - name: Checout to nova-utils
        uses: actions/checkout@v2
        with:
          repository: nova-wallet/nova-utils
          ref: 'feature/xcm_tests'
          path: nova-utils
          token: ${{ secrets.PAT }}

      - name: Debug
        run: |
          ls -R
        shell: bash

      - name: Set up actual paths
        uses: ./nova-utils/.github/workflows/setup-path

      - name: Install dependencies
        run: pip install -r nova-utils/requirements.txt

      - name: Run test
        run: |
          cd ./nova-utils
          python -m pytest --rootdir . --alluredir=allure-results/ -n auto "${{ matrix.tests }}" --reruns ${{ env.TEST_RE_RUNS }} --reruns-delay ${{ env.TEST_RE_RUNS_DELAY }}

      - name: Tar files
        if: always()
        run: |
          cd ./nova-utils
          tar -cvf allure-results.tar allure-results/

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure
          path: ./nova-utils/allure-results.tar

  make-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/report
        with:
          sub-folder: ${{ env.SUB_FOLDER }}
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          keep-reports-history: 30
          artifact-name: allure
          artifact-path: nova-utils
