name: Check nodes availability

on:
  workflow_dispatch:
  pull_request:

env:
  TEST_RE_RUNS: 1
  TEST_RE_RUNS_DELAY: 10

jobs:
  test:
    name: ${{ matrix.tests }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        tests:
          [
            test_nodes_availability,
            test_network_parameters,
            test_xcm_data,
          ]
    steps:
      - name: Checout to nova-utils
        uses: actions/checkout@v2
        with:
          repository: nova-wallet/nova-utils
          ref: 'feature/xcm_tests'
          path: nova-utils
          token: ${{ secrets.PAT }}

      - name: Debug
        run: |
          ls -R
        shell: bash

      - name: Set up actual paths
        uses: ./nova-utils/.github/workflows/setup-path

      - name: Install dependencies
        run: pip install -r nova-utils/requirements.txt

      - name: Run test
        continue-on-error: true
        run: |
          cd ./nova-utils
          python -m pytest --rootdir . --alluredir=allure-results/ -n auto "./tests/${{ matrix.tests }}.py" --reruns ${{ env.TEST_RE_RUNS }} --reruns-delay ${{ env.TEST_RE_RUNS_DELAY }}

      - name: Tar files
        if: always()
        run: |
          cd ./nova-utils
          tar -cvf allure-results.tar allure-results/

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ matrix.tests }}
          path: ./nova-utils/allure-results.tar

  make-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          path: nova-utils

      - name: Unzip results
        run: |
          tar -xvf nova-utils/test_nodes_availability/allure-results.tar
          tar -xvf nova-utils/test_network_parameters/allure-results.tar
          tar -xvf nova-utils/test_xcm_data/allure-results.tar

      - uses: ./.github/workflows/report
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          keep-reports-history: 30
